// Canonical master library, generated from "Video Game Log - Master.csv".
// Backs the "Master Library" restore action in the Profile tab — the default
// baseline a user can always reset to. Regenerate from the sheet when it changes.
// Each entry is enriched with id/cover/year at restore time (see App.jsx).
// Fields: franchise, name, completed, percent100, console (beat-on id),
//   launchConsole (id), date (bucket: "Childhood"/year/""), beatenOn (ISO or null), genre.

export const MASTER_GAMES = [
  {
    "franchise": "Sonic The Hedgehog",
    "name": "Sonic Adventure 2",
    "completed": true,
    "percent100": false,
    "console": "gamecube",
    "launchConsole": "dreamcast",
    "date": "Childhood",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Sonic The Hedgehog",
    "name": "Sonic Adventure",
    "completed": true,
    "percent100": false,
    "console": "gamecube",
    "launchConsole": "dreamcast",
    "date": "Childhood",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Sonic The Hedgehog",
    "name": "Sonic Advanced",
    "completed": true,
    "percent100": false,
    "console": "gba",
    "launchConsole": "gba",
    "date": "Childhood",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Sonic The Hedgehog",
    "name": "Sonic Frontiers",
    "completed": true,
    "percent100": false,
    "console": "switch",
    "launchConsole": "xboxseries",
    "date": "2024",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Sonic The Hedgehog",
    "name": "Sonic Frontiers Final Horizon",
    "completed": false,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Sonic The Hedgehog",
    "name": "Sonic Heroes",
    "completed": false,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Sonic The Hedgehog",
    "name": "Sonic Generations",
    "completed": false,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Sonic The Hedgehog",
    "name": "Sonic Mania",
    "completed": false,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "",
    "beatenOn": null,
    "genre": "Other"
  },
  {
    "franchise": "Sonic The Hedgehog",
    "name": "Shadow The Hedgehog",
    "completed": true,
    "percent100": false,
    "console": "emulator",
    "launchConsole": "gamecube",
    "date": "2025",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Sonic The Hedgehog",
    "name": "Shadow Generations",
    "completed": true,
    "percent100": false,
    "console": "switch",
    "launchConsole": "xboxseries",
    "date": "2025",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Super Mario",
    "name": "Super Mario 64",
    "completed": true,
    "percent100": false,
    "console": "nintendo64",
    "launchConsole": "nintendo64",
    "date": "Childhood",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Super Mario",
    "name": "Super Mario Sunshine",
    "completed": true,
    "percent100": false,
    "console": "gamecube",
    "launchConsole": "gamecube",
    "date": "Childhood",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Super Mario",
    "name": "Super Mario Galaxy",
    "completed": true,
    "percent100": false,
    "console": "switch",
    "launchConsole": "wii",
    "date": "2022",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Super Mario",
    "name": "Super Mario Galaxy 2",
    "completed": true,
    "percent100": false,
    "console": "wii",
    "launchConsole": "wii",
    "date": "2025",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Super Mario",
    "name": "Bowser's Fury",
    "completed": true,
    "percent100": false,
    "console": "switch",
    "launchConsole": "wii",
    "date": "2026",
    "beatenOn": "2026-04-02",
    "genre": "Platformer"
  },
  {
    "franchise": "Super Mario",
    "name": "Super Mario 3d World",
    "completed": true,
    "percent100": false,
    "console": "switch",
    "launchConsole": "wii",
    "date": "2026",
    "beatenOn": "2026-03-28",
    "genre": "Platformer"
  },
  {
    "franchise": "Super Mario",
    "name": "Super Mario 64 DS",
    "completed": true,
    "percent100": false,
    "console": "ds",
    "launchConsole": "ds",
    "date": "Childhood",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Super Mario",
    "name": "Paper Mario 64",
    "completed": true,
    "percent100": false,
    "console": "emulator",
    "launchConsole": "nintendo64",
    "date": "2024",
    "beatenOn": null,
    "genre": "RPG"
  },
  {
    "franchise": "Super Mario",
    "name": "Super Mario Eclipse",
    "completed": true,
    "percent100": true,
    "console": "emulator",
    "launchConsole": "emulator",
    "date": "2025",
    "beatenOn": "2025-12-01",
    "genre": "Platformer"
  },
  {
    "franchise": "Super Mario",
    "name": "Mario RPG",
    "completed": true,
    "percent100": true,
    "console": "switch",
    "launchConsole": "snes",
    "date": "2025",
    "beatenOn": "2025-08-21",
    "genre": "RPG"
  },
  {
    "franchise": "Super Mario",
    "name": "Paper Mario TTYD",
    "completed": true,
    "percent100": false,
    "console": "gamecube",
    "launchConsole": "gamecube",
    "date": "2026",
    "beatenOn": "2026-06-11",
    "genre": "RPG"
  },
  {
    "franchise": "Super Mario",
    "name": "Super Paper Mario",
    "completed": false,
    "percent100": false,
    "console": "",
    "launchConsole": "wii",
    "date": "",
    "beatenOn": null,
    "genre": "RPG"
  },
  {
    "franchise": "Super Mario",
    "name": "Super Mario World 2",
    "completed": false,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "",
    "beatenOn": null,
    "genre": "RPG"
  },
  {
    "franchise": "Super Mario",
    "name": "Luigi's Mansion",
    "completed": false,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "",
    "beatenOn": null,
    "genre": "RPG"
  },
  {
    "franchise": "Super Mario",
    "name": "Luigi's Mansion 3",
    "completed": false,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "",
    "beatenOn": null,
    "genre": "RPG"
  },
  {
    "franchise": "Pokemon",
    "name": "Pokemon Fire Red",
    "completed": true,
    "percent100": false,
    "console": "gameboy",
    "launchConsole": "gameboy",
    "date": "Childhood",
    "beatenOn": null,
    "genre": "RPG"
  },
  {
    "franchise": "Pokemon",
    "name": "Pokemon Sapphire",
    "completed": true,
    "percent100": false,
    "console": "gameboy",
    "launchConsole": "gameboy",
    "date": "Childhood",
    "beatenOn": null,
    "genre": "RPG"
  },
  {
    "franchise": "Pokemon",
    "name": "Pokemon Ruby",
    "completed": true,
    "percent100": false,
    "console": "gameboy",
    "launchConsole": "gameboy",
    "date": "Childhood",
    "beatenOn": null,
    "genre": "RPG"
  },
  {
    "franchise": "Pokemon",
    "name": "Pokemon Emerald",
    "completed": true,
    "percent100": false,
    "console": "gameboy",
    "launchConsole": "gameboy",
    "date": "Childhood",
    "beatenOn": null,
    "genre": "RPG"
  },
  {
    "franchise": "Pokemon",
    "name": "Pokemon y",
    "completed": false,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "",
    "beatenOn": null,
    "genre": "RPG"
  },
  {
    "franchise": "Pokemon",
    "name": "Pokemon HeartGold",
    "completed": true,
    "percent100": false,
    "console": "ds",
    "launchConsole": "ds",
    "date": "2026",
    "beatenOn": "2026-06-29",
    "genre": "RPG"
  },
  {
    "franchise": "Pokemon",
    "name": "Pokemon Colesseum",
    "completed": true,
    "percent100": false,
    "console": "gamecube",
    "launchConsole": "gamecube",
    "date": "2025",
    "beatenOn": "2025-05-24",
    "genre": "RPG"
  },
  {
    "franchise": "Pokemon",
    "name": "Pokemon Snap",
    "completed": true,
    "percent100": false,
    "console": "emulator",
    "launchConsole": "nintendo64",
    "date": "2023",
    "beatenOn": null,
    "genre": "RPG"
  },
  {
    "franchise": "F-Zero",
    "name": "F-Zero GX",
    "completed": true,
    "percent100": false,
    "console": "emulator",
    "launchConsole": "gamecube",
    "date": "2023",
    "beatenOn": null,
    "genre": "Racing"
  },
  {
    "franchise": "Hazelight Studios",
    "name": "It Takes Two",
    "completed": true,
    "percent100": false,
    "console": "switch",
    "launchConsole": "xboxseries",
    "date": "2024",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Hazelight Studios",
    "name": "Split Fiction",
    "completed": true,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "2025",
    "beatenOn": null,
    "genre": "Other"
  },
  {
    "franchise": "Pac-Man",
    "name": "Pac-Man World 2",
    "completed": true,
    "percent100": false,
    "console": "xbox",
    "launchConsole": "gamecube",
    "date": "2024",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Pac-Man",
    "name": "Pac-Man World",
    "completed": true,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "2026",
    "beatenOn": null,
    "genre": "Other"
  },
  {
    "franchise": "Pac-Man",
    "name": "Pac-Man World 3",
    "completed": false,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "",
    "beatenOn": null,
    "genre": "Other"
  },
  {
    "franchise": "Banjo Kazooie",
    "name": "Banjo Kazooie",
    "completed": true,
    "percent100": true,
    "console": "emulator",
    "launchConsole": "nintendo64",
    "date": "2024",
    "beatenOn": "2024-05-06",
    "genre": "Platformer"
  },
  {
    "franchise": "Banjo Kazooie",
    "name": "Banjo Kazooie Grunty's Revenge",
    "completed": true,
    "percent100": false,
    "console": "",
    "launchConsole": "gba",
    "date": "2025",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Banjo Kazooie",
    "name": "Banjo Tooie",
    "completed": false,
    "percent100": false,
    "console": "",
    "launchConsole": "nintendo64",
    "date": "",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "Legend of Zelda",
    "name": "Legend of Zelda Ocarina of Time",
    "completed": true,
    "percent100": false,
    "console": "emulator",
    "launchConsole": "nintendo64",
    "date": "2025",
    "beatenOn": "2025-10-31",
    "genre": "Action/Adventure"
  },
  {
    "franchise": "Spongebob",
    "name": "Spongebob Battle For Bikini Bottom",
    "completed": true,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "2025",
    "beatenOn": null,
    "genre": "Platformer"
  },
  {
    "franchise": "SpongeBob",
    "name": "SpongeBob Movie",
    "completed": false,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "",
    "beatenOn": null,
    "genre": "Other"
  },
  {
    "franchise": "Lego",
    "name": "Lego Racer",
    "completed": true,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "",
    "beatenOn": null,
    "genre": "Racing"
  },
  {
    "franchise": "South Park",
    "name": "South Park Stick of truth",
    "completed": true,
    "percent100": false,
    "console": "xbox360",
    "launchConsole": "xbox360",
    "date": "2014",
    "beatenOn": null,
    "genre": "Other"
  },
  {
    "franchise": "South Park",
    "name": "South Park TFBW",
    "completed": false,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "",
    "beatenOn": null,
    "genre": "Other"
  },
  {
    "franchise": "GTA",
    "name": "GTA San Andreas",
    "completed": false,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "",
    "beatenOn": null,
    "genre": "Other"
  },
  {
    "franchise": "GTA",
    "name": "GTA Vice City",
    "completed": false,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "",
    "beatenOn": null,
    "genre": "Other"
  },
  {
    "franchise": "GTA",
    "name": "GTA V",
    "completed": false,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "",
    "beatenOn": null,
    "genre": "Other"
  },
  {
    "franchise": "Crash Bandicoot",
    "name": "Crash Bandicoot Wrath of Cortex",
    "completed": true,
    "percent100": true,
    "console": "emulator",
    "launchConsole": "xbox",
    "date": "2025",
    "beatenOn": "2025-07-03",
    "genre": "Platformer"
  },
  {
    "franchise": "Crash Bandicoot",
    "name": "Crash Bandicoot 1",
    "completed": true,
    "percent100": false,
    "console": "emulator",
    "launchConsole": "playstation",
    "date": "2026",
    "beatenOn": "2026-01-01",
    "genre": "Platformer"
  },
  {
    "franchise": "Donkey Kong",
    "name": "Donkey Kong 64",
    "completed": true,
    "percent100": false,
    "console": "nintendo64",
    "launchConsole": "nintendo64",
    "date": "2026",
    "beatenOn": "2026-02-22",
    "genre": "Platformer"
  },
  {
    "franchise": "Conker's (Rare)",
    "name": "Conker's Bad Fur Day",
    "completed": true,
    "percent100": false,
    "console": "emulator",
    "launchConsole": "nintendo64",
    "date": "2026",
    "beatenOn": "2026-05-17",
    "genre": "Platformer"
  },
  {
    "franchise": "Call of Duty",
    "name": "Call of Duty 4: Modern Warfare",
    "completed": true,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "Childhood",
    "beatenOn": null,
    "genre": "Shooter"
  },
  {
    "franchise": "Call of Duty",
    "name": "Call of Duty: World at War",
    "completed": true,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "Childhood",
    "beatenOn": null,
    "genre": "Shooter"
  },
  {
    "franchise": "Call of Duty",
    "name": "Call of Duty: Modern Warfare 2",
    "completed": true,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "Childhood",
    "beatenOn": null,
    "genre": "Shooter"
  },
  {
    "franchise": "Call of Duty",
    "name": "Call of Duty: Modern Warfare 3",
    "completed": true,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "Childhood",
    "beatenOn": null,
    "genre": "Shooter"
  },
  {
    "franchise": "Call of Duty",
    "name": "Call of Duty: Black Ops",
    "completed": true,
    "percent100": false,
    "console": "",
    "launchConsole": "",
    "date": "Childhood",
    "beatenOn": null,
    "genre": "Shooter"
  }
];
